### PR TITLE
adding powershell interface

### PR DESCRIPTION
**Pull request by nialfrancis**

### CODE REVIEW

**Comment by MaxLaumeister** [comment]
Thank you!

I went to email you a small gift of my appreciation, but the email bounced.

In any case, your contribution is much appreciated. Thanks again!

**Comment by nialfrancis** [comment]
Oh no, it's nothing. I wrote this for my own use and it's working well in
my own musiclibrary repo. Thanks to you because i don't know enough about
js to make it work myself 😂.

The email bounce is concerning though, which address was it?

Nial

**Comment by MaxLaumeister** [comment]
This is the bounce I got:

<nialfrancis@nialfrancis.tech>: host mx.zoho.com.au[103.138.128.141] said: 550
5.1.1 <nialfrancis@nialfrancis.tech> User unknown (in reply to RCPT TO
command)

**Comment by nialfrancis** [comment]
Ohhhh, did you find that address posted or guess it? It's just nial@ 😉

Nial

**Comment by MaxLaumeister** [comment]
I grabbed that email out of your git commit! Only contact info I found elsewhere online was a linkedin profile, which asked me to pay to send inmail.

**Pull request merged**
